### ISSUE TITLE
Android setup doesnt work (RN 0.44)

### ISSUE THREAD

**Issue by soapcreativegithub** [bugsnag/bugsnag-react-native#139] opened 2017-09-08 00:24 UTC
### Expected behavior
follow the setup steps and the project builds and recognises the bugsnag library

### Observed behavior
crashes app

### Steps to reproduce
just followed the setup steps

### Version
RN 0.44

![2017-09-08_10-17-14](https://user-images.githubusercontent.com/31717246/30190786-f2947e66-947f-11e7-9934-9a03279365b7.png)

**Comment by kattrali** [comment] 2017-09-08 05:32
Thanks for the report @soapcreativegithub. What version of bugsnag-react-native are you using?

**Comment by EasonLex** [comment] 2017-09-20 04:19
Hi, I got the same issue. Did you solved this problem?
RN version: 0.44, 
Bugsnag version: 2.3.2

And I found out that there is no bugsnag package in MainApplication.java file after I typed react-native link. 

Thanks for your reply.

**Comment by EasonLex** [comment] 2017-09-20 09:56
I found the solution for this issue.

Add "BugsnagReactNative.getPackage()" into getPackages() list as below:

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          BugsnagReactNative.getPackage()
      );
    }

**Comment by fractalwrench** [comment] 2017-10-06 09:24
![](https://github.trello.services/images/mini-trello-icon.png) [Android setup doesnt work (RN 0.44)](https://trello.com/c/DtEwW7b1/15-android-setup-doesnt-work-rn-044)

**Comment by kattrali** [comment] 2017-10-06 12:21
Closing as I've been unable to reproduce and more information would be needed to investigate this issue. Feel free to reopen if it persists.

**Closed by kattrali** 2017-10-06 12:21 UTC
