### ISSUE TITLE
Crash reporting using Hremes

### ISSUE THREAD

**Issue by learnyst** [bugsnag/bugsnag-react-native#403] opened 2019-09-11 08:59 UTC
### Description
Reporting unhandled crashes in android with hermes enabled

### Issue
Unhandled crash is not reported when hermes is enabled

### Environment
Android, React-native 60, Hermes enabled

Library versions:
```shell
├─ bugsnag-react-native@2.23.1
├─ react-native-code-push@5.7.0
└─ react-native@0.60.4
```

- cocoapods version (if any) (`pod -v`): NA
- iOS/Android version(s): Android api version 28
- simulator/emulator or physical device?: Physical device
- debug mode or production?: production with hermes enabled

We are using hermes with react-native. Our code is like below:
try {
//Crash code
} catch(err) {
bugsnag.notify(err)
}

1. In debug mode and with hermes the crash is reported to bugsnag
2. If we disable hermes, Then crash is reported to bugsnag in production

The above crash is not reported ONLY WITH HERMES ENABLED IN PRODUCTION.

Note: Above crash is a unhandled crash. In debug mode we get red-screen. In release mode the app screen will become blank when the exception happens but if we navigate to previous screen the app works fine.

Please resolve this issue ASAP.

**Comment by abigail-bugsnag** [comment] 2019-09-11 11:50
Hi @learnyst thanks for reaching out.
From your example code, it looks like what you are trying to report is a handled error, rather than an unhandled one. We have tested reporting errors to Bugsnag in this manner with Hermes in production mode, so we are unsure as to why this might be failing for you. 

Can you please provide more information about what you are expecting to happen and what is actually happening (with screenshots and links as appropriate)? It would be helpful to see what the error is which is not being reported.

Are you able to provide us some additional information about your code where you believe the crash is not being reported to Bugsnag? and can you provide details of how you have configured Bugsnag in your application?

**Comment by mattdyoung** [comment] 2019-09-25 12:48
Closing since we're not able to reproduce. This is likely to be a misconfiguration issue which can be resolved by following this up with support@bugsnag.com.

**Closed by mattdyoung** 2019-09-25 12:48 UTC
