### ISSUE TITLE
No Crash Report?

### ISSUE THREAD

**Issue by LiuC520** [bugsnag/bugsnag-react-native#46] opened 2016-12-16 08:45 UTC
1、debug：use your demo, it can report the crash, but after android release, can't release the crash
2、add meta-data in androidManifest and replace the appkey; 
add "apply plugin:com.bugsnag.android.gradle.BugsnagPlugin" in app/buildgradle;
add "classpath 'com.bugsnag:bugsnag-android-gradle-plugin:2.3.2' " in project/build.gradle;
add "-keepattributes SourceFile,LineNumberTable" in app/proguard-rules.pro;
But can't get the crash,after click the Button ,exit !!

**Comment by kattrali** [comment] 2016-12-17 01:43
Hi @LiuC520. The crash report should be sent after the app is restarted. Can you confirm that the report is not sent on a later run of the app?

Also, did you [add the package to your `MainApplication` file](https://github.com/bugsnag/bugsnag-react-native/blob/master/examples/android/app/src/main/java/com/examples/MainApplication.java#L25)?

**Comment by LiuC520** [comment] 2016-12-17 04:48
After crash,I restarted the app,but still no report;
I'v added the package below
            new MainReactPackage(),
            BugsnagReactNative.getPackage(),
            new PickerViewPackage(),
            new ReactVideoPackage(),
I've already push the code to github:[https://github.com/LiuC520/Demo12](https://github.com/LiuC520/Demo12)

**Comment by kattrali** [comment] 2016-12-19 19:08
Thanks for the demo code, @LiuC520. It looks like [Root is imported from `index.android.js`](https://github.com/LiuC520/Demo12/blob/master/index.android.js#L9), but within `Root.js`, [Bugsnag is never imported and used](https://github.com/LiuC520/Demo12/blob/master/src/Root.js). There is a reference to the `Client` object in a separate file, [`Root1.js`](https://github.com/LiuC520/Demo12/blob/master/src/Root1.js#L16), but this file does not seem to be imported and used anywhere. Can you try moving the client to the Root file, or importing Root1 instead?

**Comment by Andreyco** [comment] 2016-12-19 23:30
Probably this guy just posted wrong build, but the issue is there. Please see #47

**Comment by kattrali** [comment] 2016-12-19 23:46
Ah, thanks @Andreyco!

**Comment by Andreyco** [comment] 2016-12-19 23:47
No problem, working on fix, will see what I can do...

**Comment by kattrali** [comment] 2016-12-19 23:56
Closing this out in favor of #47, updating there with more info.

**Closed by kattrali** 2016-12-19 23:56 UTC
