### ISSUE TITLE
NativeClient.notifyBlocking is not a function

### ISSUE THREAD

**Issue by macnube** [bugsnag/bugsnag-react-native#53] opened 2016-12-26 13:14 UTC
Not sure if I messed something up with the installation but I did verify that both libz.tbd and libBugsnagReactNative.a are in my linked libraries in xCode. The client seems to initialize without errors. 

![image](https://cloud.githubusercontent.com/assets/7122725/21482528/dbac6cea-cb53-11e6-82f3-afb745dfe685.png)

After initializing the client in a singleton module I attempt to send a test error using client.notify and I catch the following error from the Promise:

TypeError: NativeClient.notifyBlocking is not a function
    at Client._callee$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:111239:14)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34034:29)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34308:12)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34067:13)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34034:29)
    at invoke (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34110:12)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:34155:1
    at tryCallTwo (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:33674:1)
    at doResolve (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:33829:9)
    at new Promise (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:33695:1)

**Comment by Crash--** [comment] 2016-12-26 18:48
Seems this is a regression on 1.2.0 introduced by this commit https://github.com/bugsnag/bugsnag-react-native/commit/91db6339c464498068befc46ab4aa164a71163a3 since `notifyBlocking` was only added on Android :/

**Comment by the-simian** [comment] 2016-12-30 23:22
Yes i can also confirm that Bugsnag is cucrrently broken on 1.2.0 on ios, and this is the problem.

**Comment by the-simian** [comment] 2016-12-30 23:50
references https://github.com/bugsnag/bugsnag-react-native/pull/54

**Comment by kattrali** [comment] 2016-12-31 01:34
Fixed in c172297

**Closed by kattrali** 2016-12-31 01:34 UTC
