### ISSUE TITLE
[cocoapods] <BugsnagReactNative/BugsnagReactNative.h> file not found

### ISSUE THREAD

**Issue by tejas-syook** [bugsnag/bugsnag-react-native#181] opened 2017-11-13 08:15 UTC
Hi,

Unable to build ios project for react-native. Getting the following error when trying to build:

![screen shot 2017-11-13 at 1 45 28 pm](https://user-images.githubusercontent.com/33246533/32715449-64eaaaea-c878-11e7-8c40-26f2b5d29c65.png)

Followed the instructions for installation and it works fine on macbook 1. cloned my repo on macbook 2 and tried to build the project but it is failing.

my build phases link binaries:

![screen shot 2017-11-13 at 1 48 34 pm](https://user-images.githubusercontent.com/33246533/32715557-d49bf466-c878-11e7-9ae5-b568d3a80926.png)

### Version
react-native 0.44.1
bugsnag-react-native@2.6.0
xcode 9.1

regards
Tejas

**Comment by fractalwrench** [comment] 2017-11-13 09:56
Hi @tejas-syook - thanks for the report. I'm having trouble reproducing this on a fresh project, would you be able to try the following steps after cleaning + deleting derived data?

1. `yarn add bugsnag-react-native --save`
2. `react-native link`
3. Add `#import <BugsnagReactNative/BugsnagReactNative.h>` to AppDelegate

If that doesn't work it may potentially be worth changing the order of `libBugsnagReactNative.a` so that it's at the top. Are you using npm to install everything?

**Comment by tejas-syook** [comment] 2017-11-13 15:34
I am using npm. 

Tried changing the order for libBugsnagReactNative.a, didn't work.

deleted the xcworkspace and did a pod install. Now i am getting a different error 

![screen shot 2017-11-13 at 9 02 13 pm](https://user-images.githubusercontent.com/33246533/32733739-26b659fc-c8b6-11e7-90f9-f7d3959771d8.png)

**Comment by fractalwrench** [comment] 2017-11-13 17:02
@tejas-syook that error message sounds similar to the [following Cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/2053). Does the error still occur if you delete Pods, Podfile.lock, and run `pod install` again? Setting `Build Active Architectures Only` to `NO` also appeared to work for some users.

Are you able to build the Cocoapods example project? https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component

**Comment by fractalwrench** [comment] 2017-11-16 10:00
@tejas-syook are you still running into trouble with building the project, or has this been resolved?

**Comment by tejas-syook** [comment] 2017-11-16 10:11
The error is still there. We'll update by weekend.

**Comment by MattyK14** [comment] 2017-11-16 21:05
Also getting this error with bugsnag linked.

**Comment by fractalwrench** [comment] 2017-11-17 10:23
@tejas-syook out of interest is there any difference between your first and second Macbook model? Is there any difference between your build/installation process on the two models e.g. running on a physical device on one, and a simulator on another?

**Comment by amanthegreatone** [comment] 2017-11-17 10:30
The macbook models are different, one is MD-101 mid 2012 (build error) and the other is a Retina mid 2014 (build working). Building for simulators on both. I also installed it on an iMac late 2013 but getting the same build error there also. I will try to troubleshoot over the weekend and will update.

**Comment by MattyK14** [comment] 2017-11-17 13:30
My build is successful through `react-native run-ios` but I can't build it using Xcode because `'BugsnagReactNative/BugsnagReactNative.h' file not found`

**Comment by MattyK14** [comment] 2017-11-17 13:47
[This](https://github.com/bugsnag/bugsnag-react-native/issues/8#issuecomment-253285590) worked for me.

**Comment by tejas-syook** [comment] 2017-11-18 19:50
Build Active Architecture is set to No for all projects and pods.

I tried deleting the pods and reinstalling. Didn't work!

Unlinked and removed bugsnag and now I am getting the following errors:

![screen shot 2017-11-19 at 1 18 52 am](https://user-images.githubusercontent.com/33246533/32984199-ca8f3eee-ccc7-11e7-81a3-0f1abfd5f6e8.png)

**Comment by krosti** [comment] 2017-11-19 22:17
I'm using `Xcode 9.1` and I fixed this issue importing this in this way:

`#import <BugsnagReactNative.h>`

on `AppDelegate.m`.

**Comment by wprater** [comment] 2017-11-21 04:00
Im having the same issue while Im using another Staging scheme on Xcode 9.1

Any through to why I get such an error when linking?

**Comment by kattrali** [comment] 2017-12-01 03:23
Hey everyone, there's a few different issues in a single thread, though I'll try to resolve each. I'm also going to update the title to add new details.

### Using bugsnag-react-native with CocoaPods

If using CocoaPods to import BugsnagReactNative, `react-native link [bugsnag-react-native]` should *not* be used, as the library is being included already via `libPods.a`. The resolution is to delete `libBugsnagReactNative.a` from the "Link Binaries with Libraries" section.

The [Bugsnag+CocoaPods example project](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component) explains how each of the components work together. Though its geared towards developers adding React Native to an existing iOS app, the core configuration (and Podfile) is the same, as well as the explanations of the React Native internals.

I recommend running the example app to see if it works for you, so we can more quickly narrow down what configuration is different.

As a general note, when changing files outside of Xcode (e.g. via package managers), using `Option` + Product > Clean in the Xcode menu to clear the build folder reduces headaches significantly, as its not uncommon to have Xcode build artifacts in an inconsistent state when using package managers.

### Comments

> Unlinked and removed bugsnag and now I am getting the following errors:
>
> [Screenshot]

@tejas-syook was this after opening the the *.xcodeproj and not the *.xcworkspace? I've done this myself a few times.

> Im having the same issue while Im using another Staging scheme on Xcode 9.1
>
> Any through to why I get such an error when linking?

@wprater Does the scheme use a different target? If using CocoaPods, there would need to be an entry for each target you need to use, for example:

```ruby
target 'MyApp' do
  platform :ios, '10.3'
  rn_pods
end

target 'MyAppStaging' do
  platform :ios, '10.3'
  rn_pods
end

def rn_pods
  # React Native requirements
  pod 'yoga', path: './node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => './node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GLog', :podspec => './node_modules/react-native/third-party-podspecs/GLog.podspec'
  # These seem to be the required subspecs, for some reason or other
  pod 'React', path: './node_modules/react-native', subspecs: [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ]

  pod 'BugsnagReactNative', path: './node_modules/bugsnag-react-native'
end

```

`pod install` would then link the correct target.

**Comment by amanthegreatone** [comment] 2017-12-25 17:14
I was using . xcworkspace all the while. 

@krosti your solution worked!

The issue with Mach-O linker was resolved by setting `Build Active Architectures Only` to `YES` for  for all the libraries linked for debug mode and No for staging and release.

**Closed** 2018-01-11 11:22 UTC
Labels: awaiting feedback

**Comment by tommyle** [comment] 2018-04-18 22:42
This seems to be an issue with setting up BugSnag in a project that uses CocoaPods. To resolve this issue I did the following:

1. Open your project in Xcode
2. Run open node_modules/bugsnag-react-native/cocoa
3. Drag BugsnagReactNative.xcodeproj into your Libraries group
4. Select your main project in the navigator to bring up settings
5. Under Build Phases expand the Link Binary With Libraries header
6. Scroll down and click the + to add a library
7. Find and add libBugsnagReactNative.a and libz.tbd under the Workspace group
8. ⌘+B
