### ISSUE TITLE
KScrash previously declared

### ISSUE THREAD

**Issue by zakster12** [bugsnag/bugsnag-react-native#147] opened 2017-09-29 08:02 UTC
Hello, guys. We would like to use the Bugsnag because some of the errors from Sentry are not very helpful and there are a lot of people using/recommending Bugsnag. When trying to build the project with Bugsnag already configured, we have the following error: `KScrash previously declared` and I thing it's because Sentry also uses KScrash. Is there any way we can use the both in the same project so we can decide which better fits our needs. Thank you!

![screen shot 2017-09-29 at 11 00 15 am](https://user-images.githubusercontent.com/25477229/31006472-71a1c70a-a505-11e7-9df6-68c651c06b23.png)
![screen shot 2017-09-29 at 11 00 24 am](https://user-images.githubusercontent.com/25477229/31006474-73314938-a505-11e7-9d96-a42cbd1c1217.png)

**Comment by fractalwrench** [comment] 2017-09-29 08:35
Hi @zakster12 - the cause of this is that Sentry also uses KSCrash. This should be fixed in the next release of our library, which is due imminently, as we've forked KSCrash.

What package manager are you using out of curiosity? It's possible that this could be due to a configuration issue.

**Comment by zakster12** [comment] 2017-09-29 10:51
@fractalwrench Thank you for the fast response. I am using:
`npm 5.3.0` as a package manager.

**Comment by fractalwrench** [comment] 2017-10-02 18:22
Should be fixed in latest release, please let us know if the issue isn't resolved.

**Closed by fractalwrench** 2017-10-02 18:22 UTC

**Comment by zakster12** [comment] 2017-10-03 09:19
Yes, v2.4.0 fixed the issue. Thank you!
