### ISSUE TITLE
Handled error reported as unhandled 

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-react-native#382] opened 2019-07-17 19:27 UTC
### Description
Handled error reported as unhandled.

### Issue
I have a very odd case where an exception thrown inside an async function (and handled somewhere else) is reported as unhandled by bugsnag on IOS. The application does not crash, and the error is definitely handled.
Also, can't make this happen on Android at all.

### Environment

Library versions:
```shell
react-native                      0.59.9
bugsnag-react-native              2.21.1   2.21.1
```

- iOS/Android version(s): IOS 12.3
- simulator/emulator or physical device?: Physical device
- debug mode or production?: Production

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class? Yes

Sample code.

```

export async function sample(item, a=true, b=true){

    try{
        some code...
    }
    catch(err){
        let message = err.message;
        throw new Error(message);
    }

}


// later on...

let someFun = async () => {
    

    let tasks = pending.filter(item => item.priority).map(item => {
        try{
          return sample(item, true, true);
        }
        catch{
          errors++;
          return null;
        }
    });


    for(let t of tasks){
      try{
        if(t){
          await t;
        }
      }
      catch(err){
        errors++;
      }
    }
}
```

Error is reported as thrown at ```throw new Error(message);```

**Comment by abigail-bugsnag** [comment] 2019-07-23 13:24
@cristianoccazinsp can you please write in to support@bugsnag.com with this?
We would like to be able to look at this in your account and discuss your example in more detail.

**Comment by cristianoccazinsp** [comment] 2019-07-23 14:18
Will do, thanks.

**Comment by mattdyoung** [comment] 2019-07-25 11:01
Closing for now as we've been unable to reproduce. We'll re-open this if a reproduction example can be found.

**Closed by mattdyoung** 2019-07-25 11:01 UTC
