### ISSUE TITLE
Breadcrumbs not properly treating objects as metadata on android

### ISSUE THREAD

**Issue by the-simian** [bugsnag/bugsnag-react-native#36] opened 2016-12-02 07:26 UTC
Using this line of code:
`client.leaveBreadcrumb('foo', {bar: 'baz'});`
results in the warning:
`Breadcrumb metadata is not a Map or String`

here: 
```js
  leaveBreadcrumb = (name, metadata) => {
    if (name.constructor !== String) {
      console.warn('Breadcrumb name must be a String');
      return;
    }
    if (metadata == undefined) {
      metadata = {};
    }
    if (metadata.constructor === String) {
      metadata = {'message': metadata };
    }
    if (!(metadata instanceof Map)) {
      console.warn('Breadcrumb metadata is not a Map or String'); //<---------
      return;
    }
    let type = metadata['type'] || 'manual';
    delete metadata['type'];
    NativeClient.leaveBreadcrumb({
      name,
      type,
      metadata: typedMap(metadata)
    });
```

as a result, the breadcrumbs are never left.

i can see that the incoming metadata is jsut a normal js object. it does not appear to be converted into `Map`, as-is

**Comment by the-simian** [comment] 2016-12-02 19:58
When I allow the object to pass I get TypeError: expected dynamic type 'string' but had type object. It seems related to this: https://github.com/bugsnag/bugsnag-react-native/issues/32

**Comment by the-simian** [comment] 2016-12-02 20:30
As I'm looking through this code, I see the function here:
```
/**
 * Convert an object into a structure with types suitable for serializing
 * across to native code.
 */
const typedMap = function(map) {


  const output = {};
  for (const key in map) {
    const value = map[key];
    if (value instanceof Map || value instanceof Object) {
      output[key] = {type: 'map', value: typedMap(value)};
    } else {
      const type = typeof value;
      if (allowedMapObjectTypes.includes(type)) {
        output[key] = {type: type, value: value};
      }
    }
  }
  return output;
};
```

And i can see it recursively move through the object and turns each object into a serializeable map. 

however, the check is for somethign that is an instance of Map, as in either a Map class, or Map prototype. I dont see how anything could eve pass that check, there is no Map constructor in this file (or anywhere), there is only the `typedMap` function, but it doe not return a type, just JSON

**Comment by cooperka** [comment] 2016-12-05 13:20
@the-simian, indeed this should already be fixed by https://github.com/bugsnag/bugsnag-react-native/pull/33. The new version isn't published yet, but you can fork it for now or refer to the commit hash.

`Map` is a Java type that React Native uses to bridge JS `objects`. The equivalent would be `NSDictionary` in ObjectiveC. More info about bridging [here](https://facebook.github.io/react-native/docs/native-modules-ios.html).

I'll let a BugSnag owner comment on the rest of your questions, as I don't want to mislead you by getting something wrong in terms of BugSnag's expectations. Seems like they don't have a lot of documentation or unit tests yet.

**Comment by the-simian** [comment] 2016-12-06 00:37
Is `Map` just a globally accessible object therfore? I saw (in the JS code) a check for instanceof Map, but there was no calling code that would have tried to convert the object to map. Thats why I'm confused, the check was in Js, not Java

**Comment by cooperka** [comment] 2016-12-06 02:06
@the-simian I misunderstood which `Map` you were talking about. In this case yeah it's a [JS `Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). You're right, this would never work as intended. It was probably written by someone unfamiliar with javascript 😛

Feel free to submit a PR and fix this!

**Comment by the-simian** [comment] 2016-12-06 04:41
I'd love to submit a Pr, but I was asking questions about what the (at least) Android Interface needs to be. Swapping that out with a plain-old check of an Object causes the same error as PR #33 ostensibly fixes. I also notices the 'Mapper' Alters the structure of the json a bit also... I am appreciating your responses, but I actually needed a little guidance to dig in.  I've yet to be able to post a breadcrumb to the API at all. Idk what it really wants to see.

**Comment by cooperka** [comment] 2016-12-06 13:12
In the latest release v1.1.3, the breadcrumb can **only** be a string on Android. It can be any serializable object on iOS. PR #33 should have fixed Android, and as of that change you should be able to use at least numbers and booleans. I thought it also worked for objects, but as you point out it may not. With your suggested change above, it should then work for objects too. Does that help?

**Comment by the-simian** [comment] 2016-12-07 19:48
Yeah that is helpful, let me make sure I got this right
- you must stringify every value on android
- Android must be flat therefore, as it can only be essentially a 'string dictionary'
- this means anything nested will break android
- this is totally separate from the object check

Do I have the details correct?

**Comment by cooperka** [comment] 2016-12-07 20:20
That's mostly right, but actually nested objects should also work -- they'll just be recursively flattened into a string before logging. But yes, this logic is separate from the object/map check in JS.

**Comment by the-simian** [comment] 2016-12-07 20:31
Alright I'll try to fix it, thanks for that answer its exactly what I needed

**Comment by cooperka** [comment] 2016-12-07 20:59
Good luck! I'll be happy to review a PR if you end up fixing it.

**Comment by kattrali** [comment] 2016-12-08 19:33
Thanks for the debugging, @cooperka, @the-simian - updated this in a patch just now, which will be published shortly.

**Closed** 2016-12-08 19:32 UTC

**Comment by the-simian** [comment] 2016-12-08 21:19
@kattrali (cc @cooperka)  I'll check it out, but just be aware that even with `Object` checks like you have in your patch (I already tried that), I was still getting the error:

`TypeError: expected dynamic type 'string' but had type object.`

The type-checking in the method is easy enough, but I think the Android API is still not handling *nested* object correctly as-is. I'll see for sure in a short bit, when you publish!

**Comment by kattrali** [comment] 2016-12-08 21:51
Ah, thanks for the clarification, @the-simian. I thought this was handled given #33 and 262b991. Let me know if there is a further issue.
