### ISSUE TITLE
Intermittent build failure on :bugsnag-react-native:verifyReleaseResources Gradle task

### ISSUE THREAD

**Issue by jhbertra** [bugsnag/bugsnag-react-native#452] opened 2020-04-25 14:50 UTC
### Description
Running an android build which depends on bugsnag-react-native

### Issue
Encountering a sporadic build failure on the Gradle task :bugsnag-react-native:verifyReleaseResources

Error does not occur reliably, temporary workaround is to rerun build.

### Environment

Library versions:

```shell
yarn list v1.22.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ bugsnag-react-native@2.23.7
└─ react-native@0.61.5
✨  Done in 0.76s.

```

- cocoapods version (if any) (`pod -v`): N/A (android only)
- iOS/Android version(s): N/A (build error)
- simulator/emulator or physical device?: N/A (build error)
- debug mode or production?: N/A (build error)

<details>
<summary>Error messages:</summary>

```
Execution failed for task ':bugsnag-react-native:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.4.2-5326820-linux Daemon #0: Unexpected error during compile '/home/circleci/project/node_modules/bugsnag-react-native/android/build/intermediates/res/merged/release/drawable/abc_spinner_textfield_background_material.xml', attempting to stop daemon.
  This should not happen under normal circumstances, please file an issue if it does.
```
</details>

**Comment by xander-jones** [comment] 2020-04-28 14:12
Hey @jhbertra, do you still get this same error if Bugsnag is not enabled? I am not sure if Aapt2 exception is related to Bugsnag. Are you able to produce a minimal example that can reproduce this error? Additionally, which `compileSdkVersion` are you using?

**Comment by johnkiely1** [comment] 2020-09-07 08:42
Hi @jhbertra,
Were you able to determine that is caused by the presence of Bugsnag in the application? 
Closing for now but do let us know if you are still seeing this and we will be happy to reopen and investigate further.

**Closed by johnkiely1** 2020-09-07 08:42 UTC
Labels: awaiting feedback
