### ISSUE TITLE
rnpm is deprecated

### ISSUE THREAD

**Issue by Return-1** [bugsnag/bugsnag-react-native#386] opened 2019-07-25 12:25 UTC
### Description

rnpm is deprecated

### Issue
While building the following warning is issued:

> The following packages use deprecated "rnpm" config that will stop working from next release:
>   - bugsnag-react-native: https://www.bugsnag.com/platforms/react-native-error-reporting/
> 

### Environment

This is on RN ^0.60

**Comment by mattdyoung** [comment] 2019-07-25 12:41
Duplicate of https://github.com/bugsnag/bugsnag-react-native/issues/377

We already have a project underway to unify bugsnag-react-native with the bugsnag-js codebase and the rework will remove the use of `rnpm` so this will no longer be an issue when that is released in the near future.

**Closed** 2019-07-26 07:13 UTC
