### ISSUE TITLE
StackTrace shows wrong code snippet / lines

### ISSUE THREAD

**Issue by carloscuesta** [bugsnag/bugsnag-react-native#142] opened 2017-09-14 14:54 UTC
### Expected behavior

StackTrace shows the code snippet containing the lines that produce the error exception.
/cc @sospedra 

The error is being thrown at (This is intended and always throws an error, just testing the error stacktrace): 

![screen shot 2017-09-14 at 17 02 47](https://user-images.githubusercontent.com/7629661/30437351-ab961512-996e-11e7-8479-3b8145447263.png)

### Observed behavior

StackTrace shows the last lines of the file / non relevant lines for the error.

![screen shot 2017-09-14 at 17 00 48](https://user-images.githubusercontent.com/7629661/30437400-cef02e30-996e-11e7-92a6-dc1bd8a83a18.png)

### Steps to reproduce

I'm using **code-push** to generate the application bundles with the next command. The `--outputDir` is set to the `bundle` folder.

```
$ code-push release-react appName android --outputDir bundle
```

Under the hood this command runs: 

```
$ react-native bundle \
  --assets-dest bundle \
  --bundle-output bundle/index.android.bundle \
  --dev false \
  --entry-file index.android.js \
  --platform android \
  --sourcemap-output bundle/index.android.bundle.map
```

After that, I upload the sourcemaps with the `bugsnag-sourcemaps` cli like this: 

```
$ bugsnag-sourcemaps upload \
  --api-key $API_KEY \
  --code-bundle-id $BUNDLE_ID \
  --source-map bundle/index.android.bundle.map \
  --minified-file bundle/index.android.bundle \
  --minified-url index.android.bundle \
  --upload-sources \
  --add-wildcard-prefix \
  --overwrite
```

The upload is completed successfully, when there's an error I'm able to see the specific file that throws the error. The issue comes when I try to see the lines that produced the error inside of the stacktrace.

> The most common cause of misaligned source files is uploading a bundle for a release build (set with --minified-file) with a minified URL for a debug build (set with --minified-url). In this case, the source files correspond to the release bundle but the line numbers correspond to the debug bundle.

My ` --minified-file` corresponds to a release build and the `--minified-url` also points to the production one.

Thanks!

### Version

**react-native**: 0.47.2
**bugsnag-sourcemaps**: 1.0.1
**code-push-cli**: 2.0.0-beta
**react-native-code-push**: 5.0.0-beta

**Comment by ferdicus** [comment] 2017-11-15 09:20
Same issue using `2.5.1`

Line that is causing the exception and line that is displayed in the bugsnag dashboard stacktrace are 28 lines apart.

**Comment by LowieHuyghe** [comment] 2018-01-16 09:01
I'm having the same issue with Sentry (alternative to Bugsnag). The issue seems to lie with the react-native-packager when building for android production: facebook/react-native#6946.
Hope this helps!

Source: getsentry/react-native-sentry#258

**Comment by fractalwrench** [comment] 2018-03-07 15:56
Closing as caused by https://github.com/facebook/react-native/issues/6946

**Closed by fractalwrench** 2018-03-07 15:56 UTC
